package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

// generatedRuleMarker identifies rule files this command wrote, so a rerun can
// replace them without touching rules the developer added by hand.
const generatedRuleMarker = "<!-- Generated by `ods install-skill`. Do not edit; changes belong in onyx-llm-context. -->"

// installCursorSkills renders every skill as a Cursor rule under
// .cursor/rules/ at the repo root. Enforced skills become alwaysApply rules;
// on-demand skills become agent-requested rules that Cursor attaches when
// their description matches, or on an explicit @name mention.
//
// .cursor/* is gitignored in the Onyx repo, so the private content never
// reaches a public diff. Files are real copies rather than symlinks because
// Cursor does not reliably follow symlinked rule files.
func installCursorSkills(
	cmd *cobra.Command, ui *installUI, skills []llmContextSkill, repoRoot string,
) error {
	rulesDir := filepath.Join(repoRoot, ".cursor", "rules")
	if _, err := os.Stat(rulesDir); os.IsNotExist(err) {
		// Nothing installed here before, so nothing to clean up either.
		if len(skills) == 0 {
			return nil
		}
		if rulesDir, err = ui.resolveTargetDir("Cursor rules", rulesDir); err != nil {
			return err
		}
	}

	if err := removeStaleGeneratedRules(cmd, rulesDir, skills); err != nil {
		return err
	}

	for _, skill := range skills {
		dest := filepath.Join(rulesDir, skill.Name+".mdc")
		content, err := renderCursorRule(skill)
		if err != nil {
			return fmt.Errorf("could not render rule for %s: %w", skill.Name, err)
		}
		existing, err := os.ReadFile(dest)
		if err == nil && string(existing) == content {
			_, _ = fmt.Fprintf(cmd.OutOrStdout(), "Up to date %s\n", dest)
			continue
		}
		// A file without the marker is the developer's own rule, so it is
		// never replaced without their say-so.
		if err == nil && !strings.Contains(string(existing), generatedRuleMarker) {
			if ui.resolveConflict(dest) == conflictKeepBoth {
				if err := backUpFile(cmd, dest); err != nil {
					return err
				}
			}
		}
		if err := os.WriteFile(dest, []byte(content), 0o644); err != nil {
			return fmt.Errorf("could not write %s: %w", dest, err)
		}
		_, _ = fmt.Fprintf(cmd.OutOrStdout(), "Installed %s\n", dest)
	}
	return nil
}

func renderCursorRule(skill llmContextSkill) (string, error) {
	// yaml.Marshal quotes and escapes whatever the description holds, so the
	// frontmatter stays valid however the skill author phrased it.
	frontmatter, err := yaml.Marshal(struct {
		Description string `yaml:"description"`
		AlwaysApply bool   `yaml:"alwaysApply"`
	}{skill.Description, skill.Enforced})
	if err != nil {
		return "", err
	}
	return fmt.Sprintf(
		"---\n%s---\n\n%s\n\n%s", frontmatter, generatedRuleMarker, skill.Body,
	), nil
}

// backUpFile moves a kept hand-written file to an unused _old name.
func backUpFile(cmd *cobra.Command, dest string) error {
	backup, err := backupPath(dest)
	if err != nil {
		return err
	}
	if err := os.Rename(dest, backup); err != nil {
		return fmt.Errorf("could not back up %s: %w", dest, err)
	}
	_, _ = fmt.Fprintf(cmd.OutOrStdout(), "Renamed %s -> %s\n", dest, backup)
	return nil
}

// removeStaleGeneratedRules deletes previously generated rule files whose
// skill no longer exists, identified by the marker so hand-written rules
// survive whatever they are named.
func removeStaleGeneratedRules(
	cmd *cobra.Command, rulesDir string, skills []llmContextSkill,
) error {
	current := make(map[string]bool, len(skills))
	for _, skill := range skills {
		current[skill.Name+".mdc"] = true
	}

	entries, err := os.ReadDir(rulesDir)
	if err != nil {
		return fmt.Errorf("could not read %s: %w", rulesDir, err)
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".mdc") {
			continue
		}
		if current[entry.Name()] {
			continue
		}
		path := filepath.Join(rulesDir, entry.Name())
		content, err := os.ReadFile(path)
		if err != nil {
			// An unreadable rule cannot be told apart from a stale one, so
			// leaving it silently would break the regeneration contract.
			return fmt.Errorf("could not read %s: %w", path, err)
		}
		if !strings.Contains(string(content), generatedRuleMarker) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("could not remove stale rule %s: %w", path, err)
		}
		_, _ = fmt.Fprintf(cmd.OutOrStdout(), "Removed %s\n", path)
	}
	return nil
}
