package cmd

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/term"

	"github.com/onyx-dot-app/onyx/tools/ods/internal/prompt"
)

// conflictChoice is what to do with a hand-written file whose name an
// installed skill wants.
type conflictChoice int

const (
	conflictOverwriteAll conflictChoice = iota
	conflictOverwriteOne
	conflictKeepBoth
)

// installUI carries the interactive decisions of an install run. The prompt
// functions are fields so tests can drive them; the zero value of
// `interactive` gives every non-TTY run (CI, pipes) safe defaults instead of
// blocking on stdin.
type installUI struct {
	interactive bool
	out         io.Writer

	confirm    func(question string) bool
	readString func(question string) string
	choose     func(header string, options []string, defaultIndex int) int

	// Set once the user picks "overwrite all conflicts".
	overwriteAll bool
}

func newInstallUI(out io.Writer) *installUI {
	return &installUI{
		interactive: term.IsTerminal(int(os.Stdin.Fd())),
		out:         out,
		confirm:     prompt.Confirm,
		readString:  prompt.String,
		choose:      prompt.Choose,
	}
}

// resolveTargetDir returns the directory to install into, asking before the
// default is created. A declined default prompts for a directory of the
// user's own. Non-interactive runs keep the old behavior: the default is
// created without a question.
func (ui *installUI) resolveTargetDir(kind, defaultDir string) (string, error) {
	if _, err := os.Stat(defaultDir); err == nil {
		return defaultDir, nil
	}
	if ui.interactive && !ui.confirm(
		fmt.Sprintf("%s directory %s does not exist. Create it? [Y/n]: ", kind, defaultDir),
	) {
		defaultDir = ui.readString(
			fmt.Sprintf("Directory to install %s into: ", strings.ToLower(kind)),
		)
	}
	if err := os.MkdirAll(defaultDir, 0o755); err != nil {
		return "", fmt.Errorf("could not create %s: %w", defaultDir, err)
	}
	return defaultDir, nil
}

// resolveConflict decides what happens to a hand-written file at dest that an
// installed skill would replace. Non-interactive runs keep both, so a script
// can never destroy a file the user wrote.
func (ui *installUI) resolveConflict(dest string) conflictChoice {
	if ui.overwriteAll {
		return conflictOverwriteOne
	}
	if !ui.interactive {
		_, _ = fmt.Fprintf(
			ui.out, "Keeping hand-written %s as an _old backup (non-interactive)\n", dest,
		)
		return conflictKeepBoth
	}
	choice := ui.choose(
		fmt.Sprintf("%s exists and was not generated by this command.", dest),
		[]string{
			"Overwrite all conflicts",
			"Overwrite this one",
			"Keep mine, renamed with _old",
		},
		int(conflictKeepBoth),
	)
	if conflictChoice(choice) == conflictOverwriteAll {
		ui.overwriteAll = true
		return conflictOverwriteOne
	}
	return conflictChoice(choice)
}

// backupPath is where a kept hand-written file moves: its name with `_old`
// before the extension, numbered past an existing backup so a second conflict
// never overwrites the first one's backup.
func backupPath(dest string) (string, error) {
	ext := filepath.Ext(dest)
	base := strings.TrimSuffix(dest, ext) + "_old"
	for i := 1; i <= maxBackups; i++ {
		candidate := base + ext
		if i > 1 {
			candidate = fmt.Sprintf("%s%d%s", base, i, ext)
		}
		// Lstat, so a dangling symlink still counts as taken and is
		// numbered past rather than replaced.
		if _, err := os.Lstat(candidate); os.IsNotExist(err) {
			return candidate, nil
		}
	}
	return "", fmt.Errorf("no free backup name for %s after %d tries", dest, maxBackups)
}

// More backups of one file than this means something is very wrong.
const maxBackups = 100
