name: "Build Integration Image"
description: "Builds and pushes the integration test image with docker bake"
inputs:
  runs-on-ecr-cache:
    description: "ECR cache registry from runs-on/action"
    required: true
  ref-name:
    description: "Git ref name used for cache suffix fallback"
    required: true
  pr-number:
    description: "Optional PR number for cache suffix"
    required: false
    default: ""
  github-sha:
    description: "Commit SHA used for cache keys"
    required: true
  run-id:
    description: "GitHub run ID used in output image tag"
    required: true
  docker-username:
    description: "Docker Hub username"
    required: true
  docker-token:
    description: "Docker Hub token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # ratchet:docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # ratchet:docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-token }}

    - name: Format branch name for cache
      id: format-branch
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        REF_NAME: ${{ inputs.ref-name }}
      run: |
        if [ -n "${PR_NUMBER}" ]; then
          CACHE_SUFFIX="${PR_NUMBER}"
        else
          # shellcheck disable=SC2001
          CACHE_SUFFIX=$(echo "${REF_NAME}" | sed 's/[^A-Za-z0-9._-]/-/g')
        fi
        echo "cache-suffix=${CACHE_SUFFIX}" >> "$GITHUB_OUTPUT"

    - name: Build and push integration test image with Docker Bake
      shell: bash
      env:
        RUNS_ON_ECR_CACHE: ${{ inputs.runs-on-ecr-cache }}
        TAG: nightly-llm-it-${{ inputs.run-id }}
        CACHE_SUFFIX: ${{ steps.format-branch.outputs.cache-suffix }}
        HEAD_SHA: ${{ inputs.github-sha }}
      run: |
        docker buildx bake --push \
          --set backend.cache-from=type=registry,ref=${RUNS_ON_ECR_CACHE}:backend-cache-${HEAD_SHA} \
          --set backend.cache-from=type=registry,ref=${RUNS_ON_ECR_CACHE}:backend-cache-${CACHE_SUFFIX} \
          --set backend.cache-from=type=registry,ref=${RUNS_ON_ECR_CACHE}:backend-cache \
          --set backend.cache-from=type=registry,ref=onyxdotapp/onyx-backend:latest \
          --set backend.cache-to=type=registry,ref=${RUNS_ON_ECR_CACHE}:backend-cache-${HEAD_SHA},mode=max \
          --set backend.cache-to=type=registry,ref=${RUNS_ON_ECR_CACHE}:backend-cache-${CACHE_SUFFIX},mode=max \
          --set backend.cache-to=type=registry,ref=${RUNS_ON_ECR_CACHE}:backend-cache,mode=max \
          --set integration.cache-from=type=registry,ref=${RUNS_ON_ECR_CACHE}:integration-cache-${HEAD_SHA} \
          --set integration.cache-from=type=registry,ref=${RUNS_ON_ECR_CACHE}:integration-cache-${CACHE_SUFFIX} \
          --set integration.cache-from=type=registry,ref=${RUNS_ON_ECR_CACHE}:integration-cache \
          --set integration.cache-to=type=registry,ref=${RUNS_ON_ECR_CACHE}:integration-cache-${HEAD_SHA},mode=max \
          --set integration.cache-to=type=registry,ref=${RUNS_ON_ECR_CACHE}:integration-cache-${CACHE_SUFFIX},mode=max \
          --set integration.cache-to=type=registry,ref=${RUNS_ON_ECR_CACHE}:integration-cache,mode=max \
          integration
